<!-- CABECERA -->
<div id="header">
	<div id="header-bar-outer">
		<div id="header-bar-bg"></div>
	</div>
</div>

<!-- FOOTER -->
<div id="footer">
	<div id="footer-bar">
		<div class="footer-bar-inside">
			<div class="right-stuff">
			<?php if ($this->languageCode == 'es'){?>
				<a class="right-stuff-option" href="<?php echo URL_COM_ES; ?>" target="_blank">
					<?php echo $this->translate('join.the.gzaasers');?>
					<span id="mini_twitter" class="community_mini_icon"><i></i></span>
					<span id="mini_facebook" class="community_mini_icon"><i></i></span>
				</a>
				<span class="vr"></span>
				<a class="right-stuff-option" href="<?php echo URL_WTF_ES; ?>" target="_blank">&iquest;Qu&eacute; es gzaas?</a>
			<?php } else {?>
				<a class="right-stuff-option" href="<?php echo URL_COM_EN; ?>" target="_blank">
					Join the gzaasers
					<span id="mini_twitter" class="community_mini_icon">t</span>
					<span id="mini_facebook" class="community_mini_icon">f</span>
				</a>
				<span class="vr"></span>
				<a class="right-stuff-option" href="<?php echo URL_WTF_EN; ?>" target="_blank">What is gzaas?</a>
			<?php } ?>
			</div>
		</div>
	</div>
</div>


<!-- SIDEBAR -->
<div id="right_sidebar">
	<a id="random_explore" class="seegsbtn" href="<?php echo $this->baseUrl;?>/explore" title="<?php echo $this->translate('title.view.examples');?>">&gt;</a>
</div>

<!-- CONTENEDOR: LOGO + FORMULARIO + INFO GZAAS -->
<div class="center-vertical-container">
	<div id="container">
		<div id="index_screen">
			<h1 id="title">
				<img id="img_title" src="<?php echo $this->baseImage?>gzaas_logo.png" alt="gzaas logo"/>
			</h1>
			<span class="subtitle"><?php echo $this->translate('slogan');?></span>
		</div>

		<div id="form_container">
			<form action="<?php echo $this->baseUrl?>/preview/preview" name="new_gs">
				<textarea placeholder="<?php echo $this->translate('Enter your message...');?>" rows="1" cols="50" name="gs_form" id="gs_form"></textarea>
				<input type="text" class="hidden_form" name="from" value="home"></input>
				<input type="text" class="hidden_form" name="style" value="random"></input>
				<div id="preview_container">
					<span id="preview_button_container">
					<input id="preview_button" class="large_button gs_button" type="submit" value="<?php echo $this->translate('gzaas.it');?>" title="<?php echo $this->translate('title.gzaas.it');?>"></input>
					</span>
				</div>
			</form>
		</div>
	</div>
</div>

<!-- JAVASCRIPT -->

<script type="text/javascript">
var page = "home";
</script>
