<!-- CABECERA -->
<div id="header">
	<div id="header-bar-outer">
		<div id="header-bar-bg"></div>
	</div>
</div>

<!-- FOOTER -->
<div id="footer">
	<div id="footer-bar">
		<div class="footer-bar-inside">
			<div class="right-stuff">
			<?php if ($this->languageCode == 'es'){?>
				<a class="right-stuff-option" href="<?php echo URL_COM_ES; ?>" target="_blank">
					<?php echo $this->translate('join.the.gzaasers');?>
					<span id="mini_twitter" class="community_mini_icon">t</span>
					<span id="mini_facebook" class="community_mini_icon">f</span>
				</a>
				<span class="vr"></span>
				<a class="right-stuff-option" href="<?php echo URL_WTF_ES; ?>" target="_blank">&iquest;Qu&eacute; es gzaas?</a>
			<?php } else {?>
				<a class="right-stuff-option" href="<?php echo URL_COM_EN; ?>" target="_blank">
					Join the gzaasers
					<span id="mini_twitter" class="community_mini_icon">t</span>
					<span id="mini_facebook" class="community_mini_icon">f</span>
				</a>
				<span class="vr"></span>
				<a class="right-stuff-option" href="<?php echo URL_WTF_EN; ?>" target="_blank">What is gzaas?</a>
			<?php } ?>
			</div>
		</div>
	</div>
</div>


<!-- SIDEBAR -->
<div id="right_sidebar">
	<a id="random_explore" href="<?php echo $this->baseUrl;?>/explore" title="<?php echo $this->translate('title.view.examples');?>">&gt;</a>
</div>

<!-- CONTENEDOR: LOGO + FORMULARIO + INFO GZAAS -->
<div id="container">
	<div id="index_screen">
		<h1 id="title">
			<img id="img_title" src="<?php echo $this->baseImage?>gzaas_logo.png" alt="gzaas logo"/>
		</h1>
		<span class="subtitle"><?php echo $this->translate('slogan');?></span>
	</div>

	<div id="form_container">
		<form action="<?php echo $this->baseUrl?>/preview/preview" name="new_gs">
			<textarea rows="1" cols="50" name="gs_form" id="gs_form"></textarea>
			<input type="text" class="hidden_form" name="from" value="home"></input>
			<input type="text" class="hidden_form" name="style" value="random"></input>
			<div id="preview_container">
				<span id="preview_button_container">
				<input id="preview_button" class="large_button gs_button" type="submit" value="<?php echo $this->translate('gzaas.it');?>" title="<?php echo $this->translate('title.gzaas.it');?>"></input>
				</span>
			</div>
		</form>
	</div>
</div>

<a class="fork-github" href="https://github.com/ojoven/gzaas"><img style="z-index:999; position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/652c5b9acfaddf3a9c326fa6bde407b87f7be0f4/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6f72616e67655f6666373630302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png"></a>

<!-- JAVASCRIPT -->

<script type="text/javascript">
var page = "home";
</script>
