<!-- CABECERA -->
<div id="header">
	<div id="header-bar-outer">
		<div id="header-bar-bg"></div>
	</div>
</div>

<!-- CONTENEDOR: LOGO + FORMULARIO + INFO GZAAS -->
<div id="container">
	<h1>Test</h1>
</div>

<!-- FOOTER -->
<div id="footer">
	<div id="footer-bar">
		<div class="footer-bar-inside">
		</div>
	</div>
</div>

<!-- JAVASCRIPT -->

<script type="text/javascript">
var page = "test";
</script>
