<?php
$message = $this->message;
$features = $this->features;
$screenFeatures = $this->screenFeatures;

$languageCode = $this->languageCode;
if ($languageCode=='es'){
	$iLikeLanguage = 'locale=es_ES?';
}
else {
	$iLikeLanguage = 'locale=en_US?';
}
?>
<STYLE TYPE="text/css" MEDIA=screen>
body, #gzaas_screen {
cursor:pointer;
}

#gzaas_screen {

position: absolute;
text-align:center;

font-size: <?php echo $features['font']['size'];?>px;
font-family: <?php echo $features['font']['fontFamily'];?>, Verdana, Arial;
letter-spacing: -<?php echo $features['font']['fontBaseLetterSpacing'];?>px;
line-height:<?php echo $features['font']['fontBaseLineHeight'];?>px;
color: <?php echo $features['color']['color'];?>;
text-shadow: <?php echo $features['shadows']['shadows'];?>;

/* Ocultamos hasta que se posicione el div */
}



#url_gzaas, #go_home_gzaas, #info_title, #random_explore, #gs_head_left {
color:<?php echo $features['color']['color'];?>;
opacity:0;
}


body {
	background: <?php if ($features['pattern']['used']){ echo $features['pattern']['pattern'].' '; } ?>
}

</STYLE>

<div id="gzaas_screen"><?php echo $message;?></div>


<!-- HIDDEN MODULES -->
<span id="url_key" style="display:none;"><?php echo $this->urlKey; ?></span>

<script>
var page = "seegzaas";
var oldFontSize = <?php echo $features['font']['fontBaseSize'];?>;
var oldLineHeight = <?php echo $features['font']['fontBaseLineHeight'];?>;
var oldLetterSpacing = <?php echo $features['font']['fontBaseLetterSpacing'];?>;
</script>
