<STYLE TYPE="text/css" MEDIA=screen>

.all_option {
    background-image: url("http://gzaas.com/images/allfonts.png");
}


</STYLE>

<span id="all_options_title">
    <?php echo $this->translate('select.font.gallery.title');?>  
    <span class="close">X</span>
</span>
<div id="all_options_content">
	<?php 
	$count = 0;
	foreach ($this->fonts as $font){
		?>
		<div class="all_option_supra">
			<span class="all_option_name"><?php echo $font['description']?></span>		
			<span class="all_option" style="padding:0px;height:33px;background-position: -1px -<?php echo ($count*34)?>px">
				<span class="add_hashtag"><?php echo $this->translate('use.it');?></span>
				<span class="hash_key"><?php echo $font['font']?></span>
				<span class="meta_key"><?php echo '1';?></span>
			</span>
		</div>

	<?php 
	$count++;
	}?>
	<div id="all_options_credits">
		<div class="content">
			<span class="title"><?php echo $this->translate('fonts.thanks');?></span>
			<a href="#" class="link_external" target="_blank">Google Webfonts</a><span class="dark_separator">
			    <?php echo $this->translate('and.conjunction');?>
			</span>
			<a href="#" class="link_external" target="_blank">Font Squirrel</a><span class="dark_separator">|</span>
			<a href="#" class="link_external" target="_blank"><?php echo $this->translate('see.all.font.credits');?></a>
		</div>
		<div class="content">
			<span class="title"><?php echo $this->translate('gzaaser.take.part');?></span>
			<a href="#" class="link_external" target="_blank"><?php echo $this->translate('send.font.suggestions');?></a>
		</div>
	</div>
</div>	

	
	<script type="text/javascript">

	$(document).ready(function(){

		$(".all_option_supra").hover(function(e){
				$(this).find('span[class="add_hashtag"]').show();
			},
			function(e){
				$(this).find('span[class="add_hashtag"]').hide();
		});			

		$(".all_option_supra").click(function(e){
			hashtag = $(this).find('span[class="hash_key"]').html();
			$('#font').val(hashtag);
			$('#refresh_button').click();	
		});		

		$("#all_options_title .close").click(function(e){
			$("#mask,#all_options_container").hide();
			return false;
		});				

	});

	</script>