
<STYLE TYPE="text/css" MEDIA=screen>
	.all_option { background-image: url("http://gzaas.com/images/allpatterns.png"); }
</STYLE>

<div id="all_options_title">
    <?php echo $this->translate("Select a pattern from our marvellous gallery!");?>
    <span class="close">X</span>
</div>

<div id="all_options_content">
	<?php
	$count = 0;
	foreach ($this->patterns as $pattern){
		$urlPattern = PUBLIC_WEB_PATH.'/images/patterns/'.$pattern['server'].'/'.$pattern['url'];
		?>
		<div class="all_option_supra" data-hashkey="<?php echo $pattern['pattern']; ?>" data-urlpattern="<?php echo $urlPattern; ?>" data-metakey="<?php echo 4; ?>">
		<span class="all_option_name"><?php echo $pattern['description']?></span>
			<span class="all_option" style="padding:0px;height:33px;background-position: -1px -<?php echo ($count*34)?>px">
				<span class="add_hashtag"><?php echo $this->translate('use it');?></span>
			</span>
		</div>
	<?php
	$count++;
	}?>
	<div id="all_options_credits">
		<div class="content">
			<span class="title"><?php echo __("Patterns brought to you thanks to:"); ?></span>
			<a href="#" class="link_external" target="_blank">Background Labs</a><span class="dark_separator">
			    <?php echo $this->translate('and');?>
			</span>
			<a href="#" class="link_external" target="_blank">Colour Lovers</a><span class="dark_separator">|</span>
			<a href="#" class="link_external" target="_blank"><?php echo __("See all pattern credits:"); ?></a>
		</div>
		<div class="content">
			<span class="title"><?php echo __("Gzaaser! You can take part:"); ?></span>
			<a href="#" class="link_external" target="_blank"><?php echo __("Send us your pattern suggestions"); ?></a>
		</div>
	</div>
</div>


<script type="text/javascript">

	$(document).ready(function(){

		$(".all_option_supra").hover(function(e){
			$(this).find('span[class="add_hashtag"]').show();
		}, function(e){
			$(this).find('span[class="add_hashtag"]').hide();
		});

		$(".all_option_supra").click(function(e){
			var selector = $(this);
			reRenderPreview(selector);
			closeAllOptionsPopover();
		});

		$("#all_options_title .close").click(function(e){
			closeAllOptionsPopover();
			return false;
		});

	});

</script>