<?php
$renderedMessage = $this->renderedMessage;
$formMessage = $this->formMessage;
$features = $this->features;
$from = $this->from;

// Tamaño de lista de opciones (hashtags) en menú
$showHashtags = 8;

$fontUsed = $features['font']['used'];
$colorUsed = $features['color']['used'];
$backColorUsed = $features['backColor']['used'];
$patternUsed = $features['pattern']['used'];
$styleUsed = $features['style']['used'];
$shadowsUsed = $features['shadows']['used'];

//$explodeStyle = $this->explodeStyle;
$explodeStyle = 1;

?>

<STYLE TYPE="text/css" MEDIA=screen>

#gzaas_screen {

position: absolute;
text-align:center;
z-index:-1;

font-family: <?php echo $features['font']['fontFamily'];?>, Verdana, Arial;
font-size: <?php echo $features['font']['fontBaseSize'];?>px;
line-height:<?php echo $features['font']['fontBaseLineHeight'];?>px;
letter-spacing: -<?php echo $features['font']['fontBaseLetterSpacing'];?>px;
color: <?php echo $features['color']['color'];?>;

/* Ocultamos hasta que se posicione el div */
display:block;
}


body {
background: <?php if ($features['pattern']['used']!=''){echo $features['pattern']['pattern'].' ';}?><?php echo $features['backColor']['backColor'];?>;
overflow:hidden;
}


#color_span { background: <?php echo $features['color']['color'];?>; }
#backColor_span { background: <?php echo $features['backColor']['backColor'];?>; }
#pattern_span { background: <?php echo $features['pattern']['pattern'];?>; }
#mo_1 { font-family:<?php echo $features['font']['fontFamily'];?>; }

</STYLE>


<!-- Sombras -->
<div id="shadow_select_container">

		<!-- Lista de sombras añadidas -->
		<span class="metatag_submenu_title"><?php echo $this->translate('menu.shadows');?></span>
		<div id="shadow_list" <?php if($shadowsUsed){echo 'style="display:block;"';} ?>>
		<span class="metatag_submenu_options" style="margin-bottom:0px;"><?php echo $this->translate('menu.shadows');?></span>
		<?php if ($shadowsUsed) {
				$arrayShadows = explode(",",$features['shadows']['shadows']);
				if (count($arrayShadows)>0) {
						$countShad = 0;
						foreach ($arrayShadows as $shadow) {
						$countShad++;
						$arrayShad = explode(" ",trim($shadow));?>
						<ul class="shadow_list_option">
								<li class="shad_list_title"><?php echo $this->translate('menu.shadow');?> <?php echo $countShad; ?></li>
								<li><?php echo $arrayShad[0]; ?></li>
								<li><?php echo $arrayShad[1]; ?></li>
								<li><?php echo $arrayShad[2]; ?></li>
								<li class="shad_list_opt_col" style="background:<?php echo $arrayShad[3]; ?>"></li>
								<li class="shadow_clear">X</li>
								<span class="position" style="display:none"><?php echo $countShad; ?></span>
						</ul>
						<?php }
				}
		} ?>
		</div>

		<!-- Add new shadow -->
		<div id="shad_1" class="shadow_select">
				<span class="metatag_submenu_options" style="margin-bottom:10px;border-bottom: 1px solid #DDDDDD;"><?php echo $this->translate('add.new.shadow');?></span>
				<ul>
						<li>
								<label for="hor_shad"><?php echo $this->translate('horizontal');?>:</label>
								<input type="range" name="hor_shad" id="hor_shad" min="-<?php echo MAX_HOR_VER_SHADOW;?>" max="<?php echo MAX_HOR_VER_SHADOW;?>" value="0" readonly/>
						</li>
						<li>
								<label for="hor_shad"><?php echo $this->translate('vertical');?>:</label>
								<input type="range" name="ver_shad" id="ver_shad" min="-<?php echo MAX_HOR_VER_SHADOW;?>" max="<?php echo MAX_HOR_VER_SHADOW;?>" value="0" readonly/>
						</li>
						<li>
								<label for="hor_shad"><?php echo $this->translate('blur');?>:</label>
								<input type="range" name="blur_shad" id="blur_shad" min="0" max="<?php echo MAX_BLUR_SHADOW;?>" value="0" readonly/>
						</li>
						<li>
								<label for="hor_shad"><?php echo $this->translate('color');?>:</label>
								<span class="mColorPickerTrigger" id="icp_color3"><span class="shadow_fill_icon">&nbsp;</span>
										<span id="shadow_color_span">&nbsp;</span>
								</span>
								<input id="color3" type="color" data-hex="true" name="color3" value="#444444" class="color" style="display:none" />
						</li>
				</ul>
				<input type="button" id="set_new_shadow" value="<?php echo $this->translate('add.shadow');?>" />
		</div>
		<a id="go_to_new_shadow" href="#"><?php echo $this->translate('new.shadow');?></a>
		<input class="hidden_form" id="shadow_color" value="#fff" />
</div>


<!-- Warnings -->
<div id="warnings_preview"></div>


<!-- New Gzaas Created Popup -->
<div id="new_gs_container_preview" class="center_dialog">
	
	<span id="new_gs_title" class="title">
		<?php echo $this->translate('new.gs.title');?>
		<span class="subtitle"><?php echo $this->translate('new.gs.title.subtitle');?></span>
	</span>
	
	<div class="container">

		<span id="new_gs_subtitle" class="subtitle"></span>
		<a href="#" id="to_preview" class="link_external" target="_blank" title="<?php echo $this->translate('title.see.result');?>"><?php echo $this->translate('see.result');?></a>
		<input name="url_result" id="url_result" value="" type="text">
		<?php if ($this->languageCode=='es') {
			$whereToGzaas = 'http://gzaas.com/project/es/sobre-gzaas/donde-gzaasear/';
		} else {
			$whereToGzaas = 'http://gzaas.com/project/about/where-to-share-your-gzaas/';
		} ?>
		<a href="<?php echo $whereToGzaas;?>" class="more_info link_external" target="_blank"><?php echo $this->translate('where.to.gzaas');?></a>

		<p id="result_social">
			<a href="#" target="_blank" id="new_gs_twitter" class="social_preview" title="<?php echo $this->translate('title.share.twitter');?>">twitter</a>
			<a href="#" target="_blank" id="new_gs_facebook" class="social_preview" title="<?php echo $this->translate('title.share.facebook');?>">facebook</a>
		</p>

		<p id="result_private">
			<span id="result_private_advice"><?php echo $this->translate('private');?></span>
			<span id="result_private_message"><?php echo $this->translate('new.gs.private');?></span>
		</p>
	</div>
</div>
<div id="new_gs_container_error" class="center_dialog">
		<span id="preview_error_title" class="title"><?php echo $this->translate('oops');?></span>

		<div id="preview_error" class="container">
				<span id="preview_error_message" class="subtitle" style="padding: 20px 20px 24px;"></span>
		</div>
</div>

<div id="gzaas_screen"><?php echo $renderedMessage;?></div>

<div id="attention">!</div>

<div id="header">
	<div id="header-bar-outer">
		<div id="header-bar-bg"></div>
		<div id="header-bar">
			<div class="header-bar-inside">
				<div class="left-stuff">
					<div id="logo_menu">
						<a href="<?php echo $this->baseUrl('/'); ?>" title="<?php echo $this->translate('title.preview.go.home');?>">gzaas!</a>
					</div>
				</div>
				<div class="central-stuff">
					<a href="#" id="gzaas_it_preview" class="preview_top_button" title="<?php echo $this->translate('title.share.it');?>"><?php echo $this->translate('share.it');?></a>
					<span id="in_new_gs_preview" class="preview_top_button" title="<?php echo $this->translate('title.generating.link');?>"><?php echo $this->translate('generating.link');?></span>
					<a href="#" id="repeat_new_gs_preview" class="preview_top_button" title="<?php echo $this->translate('title.new.gzaas');?>"><?php echo $this->translate('new.gzaas');?></a>
				</div>
				<div class="right-stuff">

				</div>
			</div>
		</div>
	</div>
</div>

<footer>
	<ul id="metatags_container">
		<?php
		$count=0;
		foreach($this->menuOptions as $menuOption){
		$count++;
		?>
		<li class="metatag_menu">

			<?php
			// Styles
			if($menuOption[0]['idM']==50){ ?>
					<span title="<?php echo $this->translate($menuOption[0]['description']);?>" class="styles" id="mo_6"><?php echo $this->translate($menuOption[0]['metaTag']);?></span>
					<span class="vr">&nbsp;</span>
					<?php }

			// Fonts
			else if ($menuOption[0]['idM']==1){?>
					<span title="<?php echo $this->translate($menuOption[0]['description']);?>" class="metatag_option" id="mo_1">
					<?php echo $features['font']['description']; ?>
					</span>
			<?php }

			// Font color
			else if ($menuOption[0]['idM']==2){?>
			<span title="<?php echo $this->translate($menuOption[0]['description']);?>" class="mColorPickerTrigger" id="icp_color1">
					<?php echo $this->translate($menuOption[0]['metaTag']);?>
			<span id="color_span">&nbsp;</span>
			</span>
			<input id="color1" type="color" data-hex="true" name="color1" value="#444444" class="color" style="display:none">
			<?php }

			// Background color
			else if ($menuOption[0]['idM']==3){?>
			<span title="<?php echo $this->translate($menuOption[0]['description']);?>" class="mColorPickerTrigger" id="icp_color2">
					<span class="fill_icon">&nbsp;</span>
					<?php if ($features['pattern']['pattern']!='') { ?>
							<span id="backColor_span" style="display:none">&nbsp;</span>
							<span id="backcolor_no_selected" class="back_no_selected">x</span>
							<?php } else { ?>
							<span id="backColor_span">&nbsp;</span>
							<span id="backcolor_no_selected" class="back_no_selected" style="display:none">x</span>
					<?php } ?>
			</span>

			<input id="color2" type="color" data-hex="true" name="color2" value="#444444" class="color" style="display:none">
			<?php }

			// Background patterns
			else if ($menuOption[0]['idM']==4){?>
			<span title="<?php echo $this->translate($menuOption[0]['description']);?>" class="metatag_option" id="mo_4">
					<span class="pattern_icon">&nbsp;</span>
					<?php if ($features['pattern']['pattern']!='') { ?>
							<span id="pattern_span">&nbsp;</span>
							<span id="pattern_no_selected" class="back_no_selected" style="display:none;">x</span>
							<?php } else { ?>
							<span id="pattern_span" style="display:none;">&nbsp;</span>
							<span id="pattern_no_selected" class="back_no_selected">x</span>
					<?php } ?>
			</span>

			<input id="color2" type="color" data-hex="true" name="color2" value="#444444" class="color" style="display:none">
			<?php }

			// Shadows
			else if ($menuOption[0]['idM']==5) { ?>
			
				<span title="<?php echo $this->translate($menuOption[0]['description']);?>" id="to_shadow">
						<?php echo $this->translate($menuOption[0]['metaTag']);?>
				</span>
					
			<?php } else {?>
			
				<span title="<?php echo $this->translate($menuOption[0]['description']);?>" class="metatag_option" id="mo_<?php echo $count;?>"><?php echo $this->translate($metaTag[0]['metaTag']);?></span>
				
			<?php }?>
			
			<!-- Metatags Submenu -->
			<ul class="metatag_submenu" id="sub_<?php echo $menuOption[0]['idM'];?>">
				<li class="metatag_submenu_title"><?php echo $this->translate($menuOption[0]['description']);?></li>
				<li class="metatag_submenu_options">
					<span><?php echo $this->translate('most.loved');?></span>
					<span class="metatag_see_all"><?php echo $this->translate('see.all');?></span>
					<span class="meta_key_span"><?php echo $menuOption[0]['idM']?></span>
				</li>
				<?php
				$countHashtags = 0;
				foreach($menuOption[1] as $hashtag){
					if (($countHashtags<$showHashtags) && ($hashtag!=null)){
					?>
					<li>
						<ul class="hashtag_menu_ul">
						<?php
						$cssHashtags = '';
						switch ($menuOption[0]['idM']){
							case 1:
								$cssHashtags = 'padding:0px;height:33px;background-image:url('.$this->baseImage.'/ffonts.png);background-repeat: no-repeat;background-position: 0px -'.($countHashtags*34).'px';
								$hashKey = $hashtag['font'];
								break;
							case 4:
								$cssHashtags = 'padding:0px;height:33px;background-image:url('.$this->baseImage.'/fpatterns.png);background-repeat: no-repeat;background-position: 0px -'.($countHashtags*34).'px';
								$hashKey = $hashtag['pattern'];
								$urlPattern = PUBLIC_WEB_PATH.'/images/patterns/'.$hashtag['server'].'/'.$hashtag['url'];
								break;
							case 50:
								$cssHashtags = 'padding:0px;height:33px;background-image:url('.$this->baseImage.'/fstyles.png);background-repeat: no-repeat;background-position: 0px -'.($countHashtags*34).'px';
								$hashKey = $hashtag['style'];
								break;
							default:
								$cssHashtags = '';
						}?>
	
							<li class="hashtag_menu" style="<?php echo $cssHashtags;?>" data-hashkey="<?php echo $hashKey;?>" data-metakey="<?php echo $menuOption[0]['idM']?>" data-urlpattern="<?php echo (isset($urlPattern)) ? $urlPattern : ""; ?>">
								<span class="hashtag_menu_description"></span>
								<span class="add_hashtag"><?php echo $this->translate('use.it');?></span>
							</li>
						</ul>
					</li>
					<?php }
					$countHashtags++;
				}
				?>
			</ul>
		</li>
		<?php }?>
	</ul>

	<div id="preview_form_container">
		<form action="<?php echo $this->baseUrl?>/preview/preview" name="new_gs">
			<textarea rows="1" cols="50" name="gs_form" id="gs_form_preview"><?php echo $formMessage;?></textarea>
			
			<div id="expand_form" title="<?php echo $this->translate('expand.form');?>">&nbsp;</div>
			<input id="font" name="font" class="hidden_form" type="hidden" value="<?php if (($explodeStyle==1) && ($fontUsed==1)) {echo $features['font']['hashtag'];}?>"></input>
			<input id="color" name="color" class="hidden_form" type="hidden" value="<?php if (($explodeStyle==1) && ($colorUsed==1)) {echo $features['color']['hashtag'];}?>"></input>
			<input id="backColor" name="backColor" class="hidden_form" type="hidden" value="<?php if (($explodeStyle==1) && ($backColorUsed==1)) {echo $features['backColor']['hashtag'];}?>"></input>
			<input id="pattern" name="pattern" class="hidden_form" type="hidden" value="<?php if (($explodeStyle==1) && ($patternUsed==1)) {echo $features['pattern']['hashtag'];}?>"></input>
			<input id="style" name="style" class="hidden_form" type="hidden" value="<?php if ($explodeStyle==0) {echo $features['style']['hashtag'];}?>"></input>

			<input id="shadows" name="shadows" type="hidden" class="hidden_form" value="<?php if (($explodeStyle==1) && ($shadowsUsed==1)) { echo $features['shadows']['hashtag']; }?>"/>

			<input type="hidden" id="visibility" class="hidden_form" name="visibility" value="<?php echo $features['visibility']?>"></input>
			<input type="hidden" class="hidden_form" name="from" value="preview"></input>

			<input id="refresh_button" type="submit" value="" title="<?php echo $this->translate('refresh');?>"></input>
		</form>
	</div>
<!--/end metatags-->
</footer>


<div id="mask">
</div>
<div id="all_options_container"></div>


<script type="text/javascript">


var mouse_is_inside = false;
var flagNewGs = 0;
var flagFormExpanded = 0;
var flagShadowMenu = 0;
var flagColorMenu = 0;
var flagBackColorMenu = 0;
var flagAttention = 0;
var flagNoMoreLines = 0;
var flagColorHover = 0;
var flagGalleryFonts = 0;
var flagGalleryPatterns = 0;
var flagGalleryStyles = 0;

var oldFontSize = <?php echo $features['font']['fontBaseSize'];?>;
var oldLineHeight = <?php echo $features['font']['fontBaseLineHeight'];?>;
var oldLetterSpacing = <?php echo $features['font']['fontBaseLetterSpacing'];?>;

// Traducciones tratadas en javascript
var messagePublic = "<?php echo $this->translate('you.are.sharing.public');?>";
var messagePrivate = "<?php echo $this->translate('you.are.sharing.private');?>";
var publicTrad = "<?php echo $this->translate('public');?>";
var privateTrad = "<?php echo $this->translate('private');?>";
var fontcolor = "<?php echo $this->translate('menu.font.color');?>";
var backgroundcolor = "<?php echo $this->translate('menu.background.color');?>";
var shadowcolor = "<?php echo $this->translate('menu.shadow.color');?>";
var messageGzaasBlank = "<?php echo $this->translate('message.gzaas.blank');?>";
var messageNoStyle = "<?php echo $this->translate('message.no.style');?>";
var messageSameColor = "<?php echo $this->translate('message.same.color');?>";
var messageGzaasedPublic = "<?php echo $this->translate('Share this link and get your friends surprised!');?>";

// Shadows
<?php if ($features['shadows']['shadows']!='') {?>
stringShadows = "<?php echo $features['shadows']['shadows']; ?>";
arrayShadows = stringShadows.split(',');
<?php } else {?>
var arrayShadows = new Array();
<?php } ?>

var from = "<?php echo $from;?>";
var page = "preview";

</script>
