<!--container-->

<STYLE TYPE="text/css" MEDIA=screen>

#featured_fonts {
border:solid 1px #444;
width:200px;
}

#all_fonts {
border:solid 1px #444;
width:200px;
}

.ff_option {
    background: none repeat scroll 0 0 #FFFFFF;
    font-size: 20px;
    height: 24px;
    overflow: hidden;
    padding: 5px;
    width: 190px;
}

body {
margin:50px;
}

</STYLE>

<span class="fonts_title">Featured Fonts</span>
<div id="featured_fonts">
<?php foreach ($this->featuredFonts as $featuredFont){?>
<div class="ff_option" style="font-family:<?php echo $featuredFont['fontFamily'];?>"><?php echo $featuredFont['description']?></div>
<?php }?>
</div>

<br/>
<span class="fonts_title">All Fonts</span>
<div id="featured_fonts">
<?php foreach ($this->fonts as $font){?>
<div class="ff_option" style="font-family:<?php echo $font['fontFamily'];?>"><?php echo $font['description']?></div>
<?php }?>
</div>