<!--container-->

<STYLE TYPE="text/css" MEDIA=screen>

#featured_list_options {
border:solid 1px #444;
width:840px;
}

#featured_all_options {
    border: 1px solid #444444;
    width: 840px;
}

.ff_option {
height:96px;
width:800px;
padding:20px;
font-size:20px;
background-repeat:repeat;
}

</STYLE>

<span class="fonts_title">Featured Patterns</span>
<div id="featured_all_options">
<?php foreach ($this->featuredPatterns as $featuredPattern){?>
<div class="ff_option" style="background-image:url('http://gzaas.com/images/patterns/<?php echo $featuredPattern['server'].'/'.$featuredPattern['url'];?>');">&nbsp;</div>
<?php }?>
</div>

<br/>
<span class="fonts_title">All Patterns</span>
<div id="featured_all_options">
<?php foreach ($this->patterns as $pattern){?>
<div class="ff_option" style="background-image:url('http://gzaas.com/images/patterns/<?php echo $pattern['server'].'/'.$pattern['url'];?>');">&nbsp;</div>
<?php }?>
</div>