<!--container-->

<STYLE TYPE="text/css" MEDIA=screen>

#featured_list_options {
border:solid 1px #444;
width:840px;
}

#featured_all_options {
border:solid 1px #444;
width:800px;
}

.ff_option {
    background-repeat: repeat;
    font-size: 70px;
    height: 28px;
    padding: 54px;
}

</STYLE>

<span class="fonts_title">Featured Styles</span>
<div id="featured_all_options">
<?php foreach ($this->featuredStyles as $featuredStyle){
if ($featuredStyle['pattern']!=null){
	$background = "background-image:url(http://gzaas.com/images/patterns/".$featuredStyle['pattern']['server']."/".$featuredStyle['pattern']['url'].");";
} 
else {
	$background = 'background-color:#'.$featuredStyle['backColor'].';';	
}
$color = 'color:#'.$featuredStyle['color'].';';
$fontFamily = 'font-family:'.$featuredStyle['fontFamily'].';';
$textShadow = 'text-shadow:'.$featuredStyle['shadow'].';';
$styleCss = $background.$color.$fontFamily.$textShadow;
?>
<div class="ff_option" style="<?php echo $styleCss;?>">
<?php echo $featuredStyle['description'];?>
</div>
<?php }?>
</div>

<br/>
<span class="fonts_title">All Styles</span>
<div id="featured_all_options">
<?php foreach ($this->allStyles as $style){
if ($style['pattern']!=null){
	$background = "background-image:url(http://gzaas.com/images/patterns/".$style['pattern']['server']."/".$style['pattern']['url'].");";
} 
else {
	$background = 'background-color:#'.$style['backColor'].';';	
}
$color = 'color:#'.$style['color'].';';
$fontFamily = 'font-family:'.$style['fontFamily'].';';
$textShadow = 'text-shadow:'.$style['shadow'].';';
$styleCss = $background.$color.$fontFamily.$textShadow;
?>
<div class="ff_option" style="<?php echo $styleCss;?>">
<?php echo $style['description'];?>
</div>
<?php }?>
</div>