<div id="new_gs_container_preview" class="center_dialog">

	<span id="new_gs_title" class="title">
		<?php echo $this->translate('new.gs.title');?>
		<span class="close">X</span>
	</span>

	<div class="container">

		<span id="new_gs_subtitle" class="subtitle"></span>
		<input name="url_result" id="url_result" value="" type="text">

		<p id="result_social">
			<!-- <a href="#" target="_blank" id="new_gs_save" class="social_preview" download><i></i><span><?php echo $this->translate('save image');?></span></a>  -->
			<a href="#" target="_blank" id="new_gs_pinterest" class="social_preview"><i></i><span><?php echo $this->translate('pin it');?></span></a>
			<a href="#" target="_blank" id="new_gs_twitter" class="social_preview"><i></i><span><?php echo $this->translate('tweet it');?></span></a>
			<a href="#" target="_blank" id="new_gs_facebook" class="social_preview"><i></i><span><?php echo $this->translate('post to facebook');?></span></a>
			<?php if ($this->action=="preview") {?>
				<a href="#" id="to_preview" class="social_preview"><i></i><span><?php echo $this->translate('see it!');?></span></a>
			<?php }?>
		</p>

	</div>

</div>