<!DOCTYPE HTML>
<html xmlns:og="http://ogp.me/ns#">
<head>

	<!--Metas-->
	<meta charset="utf-8" />
	<meta name="google-site-verification" content="7qbLb6JmNiyvhmeZkhiR2CZUm7drEFoUe6Uo_nooALs" />

	<!--[if lt IE 9]>
	<script>
	document.createElement('header');
	document.createElement('nav');
	document.createElement('article');
	document.createElement('footer');
	</script>
	<![endif]-->

	<!-- Title & Meta -->
	<?php
		$this->headTitle()->prepend('Gzaas! ');
		echo $this->headTitle();
		echo $this->headMeta();
		echo $this->facebook;
		echo $this->headLink();
		echo $this->headScript();
	?>

	<!--CSS / LESS -->
	<link rel="stylesheet" href=" <?php echo PUBLIC_WEB_PATH; ?>/css/style.css" type="text/css" media="all"/>
	<link rel="stylesheet" href=" <?php echo PUBLIC_WEB_PATH; ?>/css/fonts/Chewy/stylesheet.css" type="text/css" media="all"/>
	<?php echo $this->headLink(); ?>

	<!--Favicon & Canonical-->
	<link rel="shortcut icon" href="<?php echo $this->imgPath; ?>icons/favicon.png"/>
	<link rel="canonical" href="http://www.gzaas.com/"/>

	<script type="text/javascript">

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-21628388-1']);
	_gaq.push(['_trackPageview']);

	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();

	</script>

</head>
<body class="index">
	<?php echo $this->layout()->content; ?>
</body>

<script>
var urlBase = "<?php echo $this->serverUrl() . $this->baseUrl('/'); ?>";
</script>

	<!-- JAVASCRIPT / JQUERY -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script type="text/javascript" src="/js/jquery-migrate-1.2.1.min.js"></script>
	<script type="text/javascript" src="/js/mColorPicker.js"></script>
	<script type="text/javascript" src="/js/jquery.tools.min.js"></script>
	<script type="text/javascript" src="/js/charCount.js"></script>
	<script type="text/javascript" src="<?php echo PUBLIC_WEB_PATH; ?>/js/functions.js"></script>
</html>
