<!DOCTYPE HTML>
<html xmlns:og="http://ogp.me/ns#">
<head>

	<!--Metas-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta charset="utf-8" />
	<meta name="google-site-verification" content="7qbLb6JmNiyvhmeZkhiR2CZUm7drEFoUe6Uo_nooALs" />

	<!--[if lt IE 9]>
	<script>
	document.createElement('header');
	document.createElement('nav');
	document.createElement('article');
	document.createElement('footer');
	</script>
	<![endif]-->

	<!-- Title & Meta -->
	<?php
		$this->headTitle()->prepend('Gzaas! ');
		echo $this->headTitle();
		echo $this->headMeta();
		echo $this->facebook;
		echo $this->headLink();
		echo $this->headScript();
	?>

	<!--CSS / LESS -->
	<link rel="stylesheet" href=" <?php echo PUBLIC_WEB_PATH; ?>/css/style.css?v=<?php echo time(); ?>" type="text/css" media="all"/>
	<link rel="stylesheet" href=" <?php echo PUBLIC_WEB_PATH; ?>/css/fonts/Chewy/stylesheet.css" type="text/css" media="all"/>
	<link href='http://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
	<?php echo $this->headLink(); ?>

	<!--Favicon & Canonical-->
	<link rel="shortcut icon" href="<?php echo $this->imgPath; ?>icons/favicon.png"/>
	<link rel="canonical" href="http://www.gzaas.com/"/>

	<?php if (My_Functions::getEnv()=="production") { ?>

	<script type="text/javascript">

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-21628388-1']);
	_gaq.push(['_trackPageview']);

	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();

	</script>

	<?php }?>

</head>
<body class="<?php if(isset($this->action)) { echo $this->action; } ?>">
	<?php echo $this->layout()->content; ?>
</body>

<script>
var urlBase = "<?php echo $this->serverUrl() . $this->baseUrl('/'); ?>";
var urlAmazonS3 = "<?php echo My_Functions::getConfigValue('general','protocol')?>://<?php echo My_Functions::getConfigValue('amazon','bucket'); ?>.s3.amazonaws.com/";
</script>

	<!-- JAVASCRIPT / JQUERY -->
	<?php // Had to get jQuery from our own server instead of from CDN due to problems with PhantomJS ?>
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/jquery-migrate-1.2.1.min.js"></script>
	<script type="text/javascript" src="/js/mColorPicker.js"></script>
	<script type="text/javascript" src="/js/jquery.tools.min.js"></script>
	<script type="text/javascript" src="/js/charCount.js"></script>
	<script type="text/javascript" src="<?php echo PUBLIC_WEB_PATH; ?>/js/functions.js?v=<?php echo time(); ?>"></script>
</html>
