<!DOCTYPE HTML>
<html xmlns:og="http://ogp.me/ns#">
<head>

<!--Metas-->
<meta charset="utf-8" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">

<!--[if lt IE 9]>
<script>
	document.createElement('header');
	document.createElement('nav');
	document.createElement('article');
	document.createElement('footer');
</script>

<![endif]-->

	<?php $this->headTitle()->prepend('gzaas! ');
			echo $this->headTitle(); ?>
		<?php echo $this->headMeta() ?>
			<?php echo $this->facebook ?>
		<?php echo $this->headLink() ?>
	<?php echo $this->headScript() ?>
</head>

<body class="index" onorientationchange="mob_orientation();">
	<?php echo $this->layout()->content ?>
</body>
</html>
