<?php
$message = $this->message;
$features = $this->features;
$screenFeatures = $this->screenFeatures;
$info = $this->info;

$languageCode = $this->languageCode;
if ($languageCode=='es'){
	$iLikeLanguage = 'locale=es_ES?';
}
else {
	$iLikeLanguage = 'locale=en_US?';
}
?>
<STYLE TYPE="text/css" MEDIA=screen>

#gzaas_screen {

position: absolute;
text-align:center;

font-size: <?php echo $features['fontSize'];?>px;
font-family: <?php echo $features['fontFamily'];?>, Verdana, Arial;
letter-spacing: -<?php echo $features['letterSpacing'];?>px;
line-height:<?php echo $features['lineHeight'];?>px;
color: <?php echo $features['color'];?>;
text-shadow: <?php echo $features['textShadow'];?>;

/* Ocultamos hasta que se posicione el div */
display:none;
}

#gzaas_screen:hover {
cursor:default;
}

#url_gzaas, #go_home_gzaas, #info_title, #random_explore, #gs_head_left {
color:<?php echo $features['color'];?>;
opacity:0;
}


body {
background: <?php if ($features['backgroundImage']!=''){echo $features['backgroundImage'].' ';}?><?php echo $features['backgroundColor'];?>;
}



</STYLE>



<div id="gzaas_screen"><?php echo $message;?></div>

<script type="text/javascript">

var oldFontSize = <?php echo $features['fontSize'];?>;
var oldLetterSpacing = <?php echo $features['letterSpacing'];?>;
var oldLineHeight = <?php echo $features['lineHeight'];?>;


var oldWindowWidth = $(window).width();

var menuOpacity=1;
var flagClick = 0;

var browserName=navigator.appName;

function overflowed(){

	// CONTROL OVERFLOW VERTICAL
	divHeight = $("#gzaas_screen").height();
	topBottomHeight = 10;
	windowHeight = $(window).height();
	freeSpaceHeight = windowHeight - topBottomHeight;

	if (divHeight>freeSpaceHeight){
		oldFontSize = (parseInt(oldFontSize) * freeSpaceHeight) / divHeight;
		oldLetterSpacing = (parseInt(oldLetterSpacing) * freeSpaceHeight) / divHeight;
		oldLineHeight = (parseInt(oldLineHeight) * freeSpaceHeight) / divHeight;

		expandFont(oldFontSize,oldLetterSpacing,oldLineHeight);
	}


	// CONTROL OVERFLOW HORIZONTAL
	divWidth = $("#gzaas_screen").width();
	windowWidth = $(window).width();
	topLeftRight = 25;
	freeSpaceWidth = windowWidth - topLeftRight;


	// Controlamos aquellos gzaas que se exceden en horizontal
	if (divWidth>freeSpaceWidth){
		oldFontSize = (parseInt(oldFontSize) * freeSpaceWidth) / divWidth;
		oldLetterSpacing = (parseInt(oldLetterSpacing) * freeSpaceWidth) / divWidth;
		oldLineHeight = (parseInt(oldLineHeight) * freeSpaceWidth) / divWidth;
	}


	$("#gzaas_screen").css('width','89%');
	$("#gzaas_screen").css('left','5%');

}

function expandFont(newFontSize,newLetterSpacing,newLineHeight){

	$("#gzaas_screen").css('font-size',newFontSize+'px');
	$("#gzaas_screen").css('letter-spacing','-'+newLetterSpacing+'px');
	$("#gzaas_screen").css('lineHeight',newLineHeight+'px');
}

function resolution(){

	oldWidth = oldWindowWidth;

	windowWidth = $(window).width();
	windowHeight = $(window).height();


	newFontSize = (windowWidth/oldWidth)*oldFontSize;
	newLetterSpacing = (windowWidth/oldWidth)*oldLetterSpacing;
	newLineHeight = (windowWidth/oldWidth)*oldLineHeight;

	expandFont(newFontSize,newLetterSpacing,newLineHeight);

	divHeight = $("#gzaas_screen").height();
	marginTop = (windowHeight/2)-(divHeight/2);
	$("#gzaas_screen").css('top',marginTop+'px');

}

function gzShow(){

	$("#gzaas_screen").fadeIn(150);
	/*
	if (browserName=="Microsoft Internet Explorer"){
		setTimeout(function(){
			$("#gs_head_left, #random_explore, #go_home_gzaas").fadeIn(1300);
			},2700);
	}
	else {
		setTimeout(function(){
			$("#gs_head_left, #random_explore, #go_home_gzaas").animate({opacity:1}, 1300);
			},2700);
	}
	*/

}

$(document).ready(function(){

	overflowed();
	setTimeout('resolution()',1000);
	setTimeout('gzShow()',2000);
});
</script>

