<?php
$message = $this->message;
$features = $this->features;
$menu = $this->menu;

// Estilo utilizado previamente (crear nuevo gzaas a partir del actual)
$fontUsed = $features['font']['used'];
$colorUsed = $features['color']['used'];
$backColorUsed = $features['backColor']['used'];
$patternUsed = $features['pattern']['used'];
$styleUsed = $features['style']['used'];
$shadowsUsed = $features['shadows']['used'];

$languageCode = $this->languageCode;
if ($languageCode=='es'){
	$iLikeLanguage = 'locale=es_ES&';
} else {
	$iLikeLanguage = 'locale=en_US&';
}
?>
<style type="text/css" media=all>

<?php if (isset($this->fontstyles)) { echo $this->fontstyles; } ?>

#gzaas_screen {
	position: absolute;
	text-align:center;

	font-family: <?php echo $features['font']['fontFamily'];?>, Verdana, Arial;
	font-size: <?php echo $features['font']['fontBaseSize'];?>px;
	line-height:<?php echo $features['font']['fontBaseLineHeight'];?>px;
	letter-spacing: -<?php echo $features['font']['fontBaseLetterSpacing'];?>px;
	color: <?php echo $features['color']['color'];?>;
	text-shadow: <?php echo $features['shadows']['shadows'];?>;
}

body {
	background: <?php if ($features['pattern']['used']!=0){echo $features['pattern']['pattern'].' ';}?><?php echo $features['backColor']['backColor'];?>;
	overflow:hidden;
}


</style>

<?php
// If we're taking an screenshot we won't render header, footer and options
if (!$this->screenshot) {
?>
<div id="header">
	<div id="header-bar-outer">
		<div id="header-bar-bg"></div>
		<div id="header-bar">
			<div class="header-bar-inside">
				<div class="left-stuff">
					<div id="logo_menu">
						<a href="<?php echo $this->baseUrl('/');?>" title="<?php echo $this->translate('title.preview.go.home');?>">gzaas!</a>
					</div>
					<div id="gs_social">
						<span id="gs_twitter">
							<a href="http://twitter.com/share" class="twitter-share-button" data-url="<?php echo $this->serverUrl() . $this->baseUrl('/',true) . $this->urlKey;?>" data-count="none" data-via="gzaas" data-lang="<?php echo $languageCode;?>">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
						</span>
						<span id="gs_facebook">
							<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fgzaas.com%2F<?php echo $this->urlKey; ?>&amp;send=false&amp;layout=button_count&amp;show_faces=false&amp;width=450&amp;action=like&amp;font=tahoma&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowTransparency="true"></iframe>
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php }?>

<div id="gzaas_screen">
	<?php echo $message;?>
</div>

<?php
// If we're taking an screenshot we won't render header, footer and options
if (!$this->screenshot) {
?>

<!-- OPTIONS -->
<div id="right_sidebar">
	<a id="to-share" class="seegsbtn sharebtn" href="#"><i></i></a>
	<a id="to-new-gzaas" class="seegsbtn plusbtn" href="#">+</a>
	<a id="random_explore" class="seegsbtn" href="<?php echo URL_BASE;?>explore">&gt;</a>
</div>

<!-- SHARE POPUP -->
<?php echo $this->render("partials/share.phtml"); ?>

<!-- FOOTER -->
<div id="footer">
	<div id="footer-bar">
		<div class="footer-bar-inside">
			<div class="right-stuff">
			<?php if ($this->languageCode == 'es'){?>

				<a class="right-stuff-option" href="<?php echo URL_COM_ES; ?>" target="_blank">
					<?php echo $this->translate('join.the.gzaasers');?>
					<span id="mini_twitter" class="community_mini_icon">t</span>
					<span id="mini_facebook" class="community_mini_icon">f</span>
				</a>
				<span class="vr"></span>
				<a class="right-stuff-option" href="<?php echo URL_WTF_ES; ?>" target="_blank">&iquest;Qu&eacute; es gzaas?</a>

			<?php }
			else {?>
				<a class="right-stuff-option" href="<?php echo URL_COM_EN; ?>" target="_blank">
					Join the gzaasers
					<span id="mini_twitter" class="community_mini_icon">t</span>
					<span id="mini_facebook" class="community_mini_icon">f</span>
				</a>
				<span class="vr"></span>
				<a class="right-stuff-option" href="<?php echo URL_WTF_EN; ?>" target="_blank">What is gzaas?</a>
			<?php } ?>
			</div>
		</div>
	</div>
</div>

<div id="create_gzaas_container" class="center_dialog">
	<span class="title">
		<?php echo $this->translate('dialog.create.new.gzaas');?>
		<span class="close">X</span>
	</span>
	<div class="container">
		<form action="<?php echo $this->baseUrl('/');?>preview/preview" name="new_gs">
			<input placeholder="<?php echo $this->translate('Enter your message...');?>" type="text" class="center_dialog_input" name="gs_form" id="gs_form_create_gzaas" />
			<input id="font" name="font" class="hidden_form" type="text" value="<?php if($fontUsed){ echo $features['font']['hashtag']; }?>"></input>
			<input id="color" name="color" class="hidden_form" type="text" value="<?php if($colorUsed) { echo $features['color']['hashtag']; }?>"></input>
			<input id="backColor" name="backColor" class="hidden_form" type="text" value="<?php if($backColorUsed) { echo $features['backColor']['hashtag']; }?>"></input>
			<input id="pattern" name="pattern" class="hidden_form" type="text" value="<?php if($patternUsed) { echo $features['pattern']['hashtag']; }?>"></input>
			<input id="shadows" name="shadows" class="hidden_form" type="text" value="<?php if($shadowsUsed) { echo $features['shadows']['hashtag']; }?>"></input>
			<input id="style" name="style" class="hidden_form" type="text" value="<?php if($styleUsed) { echo $features['style']['hashtag']; }?>"></input>
			<input id="create_button" class="dialog_button btn primary" type="submit" value="<?php echo $this->translate('gzaas.it');?>">
		</form>
	</div>
</div>

<div id="screen_layer">&nbsp;</div>

<?php }?>

<script type="text/javascript">

var createGzaas = "<?php echo $this->translate('create.gzaas');?>";
var page = "seegzaas";
var screenshot = <?php echo ($this->screenshot) ? '"' . $this->screenshot . '"' : "false"; ?>;

var oldFontSize = <?php echo $features['font']['fontBaseSize'];?>;
var oldLineHeight = <?php echo $features['font']['fontBaseLineHeight'];?>;
var oldLetterSpacing = <?php echo $features['font']['fontBaseLetterSpacing'];?>;

var messageTitlePopup = "<?php echo $this->translate('Share this link and get your friends surprised!');?>";

var urlKey = "<?php echo $this->urlKey; ?>";

</script>

