<?php
$message = $this->message;
$features = $this->features;
$screenFeatures = $this->screenFeatures;
?>
<STYLE TYPE="text/css" MEDIA=screen>

#gzaas_screen {

text-align:center;

font-size: 20px;
font-family: 'Georgia','Times New Roman',serif;
width:99%;


}

</STYLE>


<div id="gzaas_screen"><?php echo $message;?></div>


<script type="text/javascript">

function resolution(){

	windowHeight = $(window).height();

	divHeight = $("#gzaas_screen").height();
	marginTop = (windowHeight/2)-(divHeight/2)-30;
	$("#gzaas_screen").css('margin-top',marginTop+'px');

}

$(document).ready(function(){

resolution();


$(window).resize(function() {
resolution();

});





});
</script>

